defaultSemverRangePrefix: ''

packageExtensions:
  '@mdx-js/loader@*':
    peerDependencies:
      react: '^16.13.1'
  '@storybook/preset-create-react-app@*':
    peerDependencies:
      typescript: '>=3.x'
      webpack: '^3.0.0 || ^4.0.0'
  '@storybook/react@*':
    peerDependencies:
      typescript: '>=3.x'
  electron-webpack-js@*:
    peerDependencies:
      webpack: '>=2'
  pnp-webpack-plugin@*:
    dependencies:
      ts-pnp: '>=1.2.0'
  rc-tooltip@*:
    peerDependencies:
      react: '^16.0.0'
      react-dom: '^16.0.0'
  rc-trigger@*:
    peerDependencies:
      react: '^16.0.0'
      react-dom: '^16.0.0'
  react-color@*:
    peerDependencies:
      react: '*'
  react-docgen-typescript-loader@*:
    peerDependencies:
      webpack: '^3.0.0 || ^4.0.0'
  react-docgen-typescript-plugin@*:
    peerDependencies:
      webpack: '^3.0.0 || ^4.0.0'
  react-scripts@*:
    dependencies:
      ts-pnp: '>=1.2.0'
  react-toastify@*:
    peerDependencies:
      react-dom: '>=16.6.0'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: '@yarnpkg/plugin-constraints'

pnpMode: loose

yarnPath: .yarn/releases/yarn-2.1.1.cjs
